# Generated by Django 5.0.4 on 2024-06-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='All our flowers are collected only after your order, which guarantees the freshness of the bouquets. For you, with love!'),
        ),
    ]
