# Generated by Django 5.0.4 on 2024-06-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
