# Generated by Django 5.0.4 on 2024-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, default='try', help_text='*The field is optional', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(default='try', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='inscription',
            field=models.CharField(default='Congratulation!', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='try', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
