# Generated by Django 5.0.4 on 2024-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_apartment_order_house_order_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.IntegerField(blank=True, help_text='*The field is optional', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
