# Generated by Django 5.0.4 on 2024-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_apartment_alter_order_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inscription',
            field=models.CharField(default='Congratulation!', help_text='*The text on the postcard', max_length=1000),
        ),
    ]
