# Generated by Django 5.0.4 on 2024-06-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inscription',
            field=models.TextField(default='Congratulation!', help_text='*The text on the postcard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.products'),
        ),
    ]
