# Generated by Django 5.0.4 on 2024-06-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_product_id_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inscription',
            field=models.TextField(default='Congratulation!', help_text='*The text on the postcard', max_length=1000),
        ),
    ]
