# Generated by Django 5.0.4 on 2024-06-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+375 xx xxx xx xx', help_text='*In the format +375 xx xxx xx xx', max_length=15),
        ),
    ]
